import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import { rajdhani, manrope } from "@/utils/font";
import { Wallet } from "@/walletAdapter/walletAdapterLib";
import { Analytics } from "@vercel/analytics/react";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/components/providers/reduxProvider";
import OfflineDetector from "@/components/useables/OfflineDetector";
import CookieConsentModal from "@/components/useables/CookieConsentModal";

export const metadata: Metadata = {
  title: "Emerg Funds Raising",
  description:
    "Emerg Funds Raising is a dedicated platform designed to help individuals and organizations quickly raise emergency funds for urgent needs. Easily create, share, and support fundraising campaigns for medical emergencies, disaster relief, and other critical situations.",
  keywords: [
    "raise money",
    "emergency funds",
    "easy funding",
    "fund raiser",
    "charity event",
    "charity events",
    "fundraising",
    "emergency funds",
    "donations",
    "charity",
    "support",
    "crowdfunding",
    "crypto fundraising",
    "medical emergencies",
    "disaster relief",
    "urgent needs",
    "fundraising platform",
    "fundraising campaigns",
    "emergency assistance",
    "community support",
    "nonprofit",
    "charitable giving",
    "fundraising solutions",
    "fundraising for medical bills",
    "fundraising for disaster relief",
    "fundraising for urgent needs",
    "fundraising for individuals",
    "fundraising for organizations",
    "fundraising for causes",
    "fundraising for emergencies",
    "fundraising for medical emergencies",
    "fundraising for disaster relief",
    "fundraising for urgent situations",
    "fundraising for community support",
    "fundraising for nonprofits",
    "fundraising for charitable causes",
    "fundraising for medical bills",
    "fundraising for disaster relief efforts",
    "fundraising for urgent needs",
    "fundraising for individuals in need",
    "fundraising for organizations in need",
    "fundraising for charitable organizations",
    "fundraising for community initiatives",
    "fundraising for emergency situations",
    "fundraising for urgent medical needs",
    "fundraising for disaster recovery",
    "fundraising for urgent community support",
    "fundraising for emergency assistance",
    "fundraising for urgent medical emergencies",
    "fundraising for disaster response",
    "fundraising for urgent relief efforts",
    "fundraising for emergency relief",
    "fundraising for urgent community initiatives",
    "fundraising for emergency situations",
    "fundraising for urgent medical situations",
    "fundraising for disaster assistance",
    "fundraising for urgent community needs",
    "fundraising for emergency medical needs",
    "fundraising for urgent disaster relief",
    "fundraising for urgent community support",
    "fundraising for emergency medical emergencies",
    "fundraising for urgent disaster response",
    "fundraising for urgent relief",
    "fundraising for emergency relief efforts",
    "fundraising for urgent community assistance",
    "fundraising for emergency situations",
    "fundraising for urgent medical emergencies",
    "fundraising for disaster relief",
    "fundraising for urgent needs",
    "fundraising for medical emergencies",
    "fundraising for disaster relief",
    "fundraising for urgent situations",
    "fundraising for community support",
    "fundraising for nonprofits",
    "fundraising for charitable causes",
    "fundraising for medical bills",
    "fundraising for disaster relief efforts",
    "fundraising for urgent needs",
    "fundraising for individuals in need",
    "fundraising for organizations in need",
    "fundraising for charitable organizations",
    "fundraising for community initiatives",
    "fundraising for emergency situations",
    "fundraising for urgent medical needs",
    "fundraising for disaster recovery",
    "fundraising for urgent community support",
    "cryptocurrency fundraising",
    "crypto donations",
    "crypto charity",
    "crypto crowdfunding",
    "crypto support",
    "crypto fundraising platform",
    "crypto fundraising campaigns",
    "crypto emergency funds",
    "crypto donations platform",
    "crypto charity platform",
    "crypto crowdfunding platform",
    "crypto support platform",
    "crypto fundraising solutions",
    "crypto fundraising for medical emergencies",
    "crypto fundraising for disaster relief",
    "crypto fundraising for urgent needs",
    "crypto fundraising for individuals",
    "crypto fundraising for organizations",
    "crypto fundraising for causes",
    "crypto fundraising for emergencies",
    "crypto fundraising for medical emergencies",
    "crypto fundraising for disaster relief",
    "crypto fundraising for urgent situations",
    "crypto fundraising for community support",
    "crypto fundraising for nonprofits",
    "crypto fundraising for charitable causes",
    "crypto fundraising for medical bills",
    "crypto fundraising for disaster relief efforts",
    "crypto fundraising for urgent needs",
    "crypto fundraising for individuals in need",
    "crypto fundraising for organizations in need",
    "crypto fundraising for charitable organizations",
    "crypto fundraising for community initiatives",
    "crypto fundraising for emergency situations",
    "crypto fundraising for urgent medical needs",
    "crypto fundraising for disaster recovery",
    "crypto fundraising for urgent community support",
    "crypto fundraising for emergency assistance",
    "crypto fundraising for urgent medical emergencies",
    "crypto fundraising for disaster response",
    "crypto fundraising for urgent relief efforts",
    "crypto fundraising for emergency relief",
    "crypto fundraising for urgent community initiatives",
    "crypto fundraising for emergency situations",
    "crypto fundraising for urgent medical situations",
    "crypto fundraising for disaster assistance",
    "crypto fundraising for urgent community needs",
    "crypto fundraising for emergency medical needs",
    "crypto fundraising for urgent disaster relief",
    "crypto fundraising for urgent community support",
    "crypto fundraising for emergency medical emergencies",
    "crypto fundraising for urgent disaster response",
    "crypto fundraising for urgent relief",
    "crypto fundraising for emergency relief efforts",
    "crypto fundraising for urgent community assistance",
    "crowdfunding platform",
    "crowdfunding campaigns",
    "crowdfunding for emergency funds",
    "crowdfunding for donations",
    "crowdfunding for charity",
    "crowdfunding for support",
    "crowdfunding for medical emergencies",
    "crowdfunding for disaster relief",
    "crowdfunding for urgent needs",
    "crowdfunding for individuals",
    "crowdfunding for organizations",
    "crowdfunding for causes",
    "crowdfunding for emergencies",
    "crowdfunding for medical emergencies",
    "crowdfunding for disaster relief",
    "crowdfunding for urgent situations",
    "crowdfunding for community support",
    "crowdfunding for nonprofits",
    "crowdfunding for charitable causes",
    "crowdfunding for medical bills",
    "crowdfunding for disaster relief efforts",
    "crowdfunding for urgent needs",
    "crowdfunding for individuals in need",
    "crowdfunding for organizations in need",
    "crowdfunding for charitable organizations",
    "crowdfunding for community initiatives",
    "crowdfunding for emergency situations",
    "crowdfunding for urgent medical needs",
    "crowdfunding for disaster recovery",
    "crowdfunding for urgent community support",
    "crowdfunding for emergency assistance",
    "crowdfunding for urgent medical emergencies",
    "gofundme",
    "kickstarter",
    "indiegogo",
    "crowdfunder",
    "patreon",
    "crowdsourcing",
    "fundraising",
    "fundraising platform",
    "fundraising campaigns",
    "fundraising for emergency funds",
    "fundraising for donations",
    "fundraising for charity",
    "fundraising for support",
    "fundraising for medical emergencies",
    "fundraising for disaster relief",
    "fundraising for urgent needs",
    "fundraising for individuals",
    "fundraising for organizations",
    "fundraising for causes",
    "crypto gofundme",
    "crypto crowdfunding",
    "crypto fundraising",
    "crypto donations",
    "crypto charity",
    "crypto support",
    "crypto fundraising platform",
    "crypto fundraising campaigns",
    "crypto emergency funds",
    "crypto donations platform",
    "crypto charity platform",
    "crypto crowdfunding platform",
    "crypto support platform",
    "crypto fundraising solutions",
    "crypto fundraising for medical emergencies",
    "crypto fundraising for disaster relief",
    "crypto fundraising for urgent needs",
    "crypto fundraising for individuals",
    "crypto fundraising for organizations",
    "crypto fundraising for causes",
    "crypto fundraising for emergencies",
    "crypto fundraising for medical emergencies",
    "blockchain crowdfunding",
    "blockchain fundraising",
    "blockchain donations",
    "blockchain charity",
    "blockchain support",
    "blockchain fundraising platform",
    "blockchain fundraising campaigns",
    "blockchain emergency funds",
    "blockchain donations platform",
    "blockchain charity platform",
    "blockchain crowdfunding platform",
    "blockchain support platform",
    "blockchain fundraising solutions",
    "blockchain fundraising for medical emergencies",
    "blockchain fundraising for disaster relief",
    "blockchain fundraising for urgent needs",
    "blockchain fundraising for individuals",
    "blockchain fundraising for organizations",
    "blockchain fundraising for causes",
    "blockchain fundraising for emergencies",
    "blockchain fundraising for medical emergencies",
    "blockchain fundraising for disaster relief",
    "blockchain fundraising for urgent situations",
    "blockchain fundraising for community support",
    "blockchain fundraising for nonprofits",
    "blockchain fundraising for charitable causes",
    "blockchain fundraising for medical bills",
    "blockchain fundraising for disaster relief efforts",
    "blockchain fundraising for urgent needs",
    "blockchain fundraising for individuals in need",
    "blockchain fundraising for organizations in need",
    "blockchain fundraising for charitable organizations",
    "blockchain fundraising for community initiatives",
    "blockchain fundraising for emergency situations",
    "blockchain fundraising for urgent medical needs",
    "blockchain fundraising for disaster recovery",
    "blockchain fundraising for urgent community support",
    "blockchain fundraising for emergency assistance",
    "blockchain fundraising for urgent medical emergencies",
    "blockchain fundraising for disaster response",
    "blockchain fundraising for urgent relief efforts",
    "blockchain fundraising for emergency relief",
    "blockchain fundraising for urgent community initiatives",
    "blockchain fundraising for emergency situations",
    "blockchain fundraising for urgent medical situations",
    "blockchain fundraising for disaster assistance",
    "blockchain fundraising for urgent community needs",
    "blockchain fundraising for emergency medical needs",
    "blockchain fundraising for urgent disaster relief",
    "solana",
    "solana crowdfunding",
    "solana fundraising",
    "solana donations",
    "solana charity",
    "solana support",
    "solana fundraising platform",
    "solana fundraising campaigns",
    "solana emergency funds",
    "solana donations platform",
    "solana charity platform",
    "solana crowdfunding platform",
    "solana support platform",
    "solana fundraising solutions",
    "solana fundraising for medical emergencies",
    "solana fundraising for disaster relief",
    "solana fundraising for urgent needs",
    "solana fundraising for individuals",
    "solana fundraising for organizations",
    "solana fundraising for causes",
    "solana fundraising for emergencies",
    "solana fundraising for medical emergencies",
    "solana fundraising for disaster relief",
    "solana fundraising for urgent situations",
    "airdrop",
    "airdrop fundraising",
    "airdrop donations",
    "airdrop charity",
    "airdrop support",
    "airdrop fundraising platform",
    "airdrop fundraising campaigns",
    "airdrop emergency funds",
    "airdrop donations platform",
    "airdrop charity platform",
    "fundraisers for schools",
    "fundraisers for education",
    "fundraisers for students",
    "fundraisers for teachers",
    "fundraisers for scholarships",
    "fundraisers for educational programs",
    "fundraisers for school supplies",
    "fundraisers for school events",
    "fundraisers for school projects",
    "fundraisers for school trips",
    "fundraisers for school renovations",
    "fundraisers for school sports",
    "fundraisers for school activities",
    "fundraisers for school clubs",
    "fundraisers for school organizations",
    "fundraisers for school charities",
    "fundraisers for school foundations",
    "fundraisers for school initiatives",
    "fundraisers for school communities",
    "fundraisers for school resources",
    "fundraisers for school programs",
    "fundraisers for school scholarships",
    "fundraisers for school supplies",
    "fundraising ideas for nonprofits",
    "fundraising ideas for charities",
    "fundraising ideas for schools",
    "fundraising ideas for community organizations",
    "fundraising ideas for medical emergencies",
    "fundraising ideas for disaster relief",
    "chipotle fundraiser",
    "panda express fundraiser",
    "fundraising events",
    "fundraising campaigns",
    "best crowdfunding sites for personal",
    "best crowdfunding sites for medical emergencies",
    "best crowdfunding sites for disaster relief",
    "best crowdfunding sites for urgent needs",
    "best crowdfunding sites for individuals",
    "best crowdfunding sites for organizations",
    "best crowdfunding sites for causes",
    "best crowdfunding sites for emergencies",
    "best crowdfunding sites for medical emergencies",
    "best crowdfunding sites for disaster relief",
    "best crowdfunding sites for urgent situations",
    "best crowdfunding sites for community support",
    "best crowdfunding sites for nonprofits",
    "best crowdfunding sites for charitable causes",
    "best crowdfunding sites for medical bills",
    "best crowdfunding sites for disaster relief efforts",
    "best crowdfunding sites for urgent needs",
    "best crowdfunding sites for individuals in need",
    "best crowdfunding sites for organizations in need",
    "best crowdfunding sites for charitable organizations",
    "best crowdfunding sites for community initiatives",
    "best crowdfunding sites for emergency situations",
    "best crowdfunding sites for urgent medical needs",
    "best crowdfunding sites for disaster recovery",
    "best crowdfunding sites for urgent community support",
    "best crowdfunding sites for emergency assistance",
    "best crowdfunding sites for urgent medical emergencies",
    "best crowdfunding sites for disaster response",
    "double good fundraiser",
    "association of fundraising professionals",
    "fundraising ideas",
    "krispy kreme fundraiser",
    "double good popcorn",
    "double good fundraiser app",
    "double good fundraiser popcorn",
    "double good fundraiser app",
    "snap raise",
    "snap raise fundraising",
    "justgiving",
    "gofundme",
    "just giving page",
  ],
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/logo.jpg", type: "image/jpg", sizes: "32x32" },
      { url: "/logo.jpg", type: "image/jpg", sizes: "192x192" },
    ],
    apple: [
      {
        url: "/apple-touch-icon.png",
        sizes: "180x180",
        type: "image/png",
      },
    ],
    shortcut: ["https://www.emergfunds.org/logo.jpg"],
    other: [
      {
        rel: "apple-touch-icon-precomposed",
        url: "https://www.emergfunds.org/logo.jpg",
      },
    ],
  },
  verification: {
    google: "your-google-site-verification",
  },
  alternates: {
    canonical: "https://www.emergfunds.org",
  },
  metadataBase: new URL("https://www.emergfunds.org"),
  openGraph: {
    title: "Emerg Funds Raising",
    description:
      "Emerg Funds Raising is a dedicated platform designed to help individuals and organizations quickly raise emergency funds for urgent needs. Easily create, share, and support fundraising campaigns for medical emergencies, disaster relief, and other critical situations.",
    siteName: "Emergency Funds Raising",
    images: [
      {
        url: "https://www.emergfunds.org/twitter-banner.jpg",
        width: 1200,
        height: 630,
        alt: "Emerg Fund Raising Platform",
      },
      {
        url: "https://www.emergfunds.org/logo.jpg",
        width: 800,
        height: 600,
        alt: "Emerg Fund Raising Platform",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Emerg Funds Raising",
    description:
      "Emerg Funds Raising is a dedicated platform designed to help individuals and organizations quickly raise emergency funds for urgent needs. Easily create, share, and support fundraising campaigns for medical emergencies, disaster relief, and other critical situations.",
    images: ["https://www.emergfunds.org/twitter-banner.jpg"],
    creator: "@emergfunds_",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo.jpg" sizes="any" />
        <link rel="icon" href="/logo.jpg" type="image/jpg" />
        <link rel="icon" href="/icon.png" type="image/png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>
      <Script src="https://api.tempo.new/proxy-asset?url=https://storage.googleapis.com/tempo-public-assets/error-handling.js" />
      <body className={`${rajdhani.variable} ${manrope.variable}`}>
        <Providers>
          <OfflineDetector />
          <Wallet>{children}</Wallet>
          <CookieConsentModal />
          <Toaster />
          <Analytics />
        </Providers>
      </body>
    </html>
  );
}
