name: Redeploy to Vercel on Main Merge

on:
  push:
    branches:
      - staging
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
